## YAML Template.
default:
  stylesheets:    [main.css]

datosSuccess:
  stylesheets: [maps.css]
  javascripts: [https://maps.google.com/maps/api/js?sensor=true , gmaps.js]
  layout: mostrardatos
  
indexSuccess:
  stylesheets: [tablas.css]
  
newSuccess:
  stylesheets: [central/sector.css]
  javascripts: [https://maps.google.com/maps/api/js?sensor=true , codigo.js,jquery-1.7.2.min.js]
  
editSuccess:
  stylesheets: [central/sector.css]
  javascripts: [https://maps.google.com/maps/api/js?sensor=true , codigo.js,jquery-1.7.2.min.js]