<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Carrera', 'doctrine');

/**
 * BaseCarrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_operador
 * @property integer $id_codigo
 * @property integer $id_vehiculo
 * @property integer $id_sincodigo
 * @property integer $tiempo
 * @property clob $detalle
 * @property date $fecha
 * @property time $hora
 * @property enum $estado
 * @property integer $tiempo_atencion
 * @property integer $destino
 * @property time $horaat
 * @property integer $tiempo_aprox_dest
 * @property time $hora_dest
 * @property integer $calidad
 * @property sfGuardUser $sfGuardUser
 * @property Codigo $Codigo
 * @property Vehiculo $Vehiculo
 * @property Sin_Codigo $Sin_Codigo
 * @property Sector $Sector
 * 
 * @method integer     getIdOperador()        Returns the current record's "id_operador" value
 * @method integer     getIdCodigo()          Returns the current record's "id_codigo" value
 * @method integer     getIdVehiculo()        Returns the current record's "id_vehiculo" value
 * @method integer     getIdSincodigo()       Returns the current record's "id_sincodigo" value
 * @method integer     getTiempo()            Returns the current record's "tiempo" value
 * @method clob        getDetalle()           Returns the current record's "detalle" value
 * @method date        getFecha()             Returns the current record's "fecha" value
 * @method time        getHora()              Returns the current record's "hora" value
 * @method enum        getEstado()            Returns the current record's "estado" value
 * @method integer     getTiempoAtencion()    Returns the current record's "tiempo_atencion" value
 * @method integer     getDestino()           Returns the current record's "destino" value
 * @method time        getHoraat()            Returns the current record's "horaat" value
 * @method integer     getTiempoAproxDest()   Returns the current record's "tiempo_aprox_dest" value
 * @method time        getHoraDest()          Returns the current record's "hora_dest" value
 * @method integer     getCalidad()           Returns the current record's "calidad" value
 * @method sfGuardUser getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method Codigo      getCodigo()            Returns the current record's "Codigo" value
 * @method Vehiculo    getVehiculo()          Returns the current record's "Vehiculo" value
 * @method Sin_Codigo  getSinCodigo()         Returns the current record's "Sin_Codigo" value
 * @method Sector      getSector()            Returns the current record's "Sector" value
 * @method Carrera     setIdOperador()        Sets the current record's "id_operador" value
 * @method Carrera     setIdCodigo()          Sets the current record's "id_codigo" value
 * @method Carrera     setIdVehiculo()        Sets the current record's "id_vehiculo" value
 * @method Carrera     setIdSincodigo()       Sets the current record's "id_sincodigo" value
 * @method Carrera     setTiempo()            Sets the current record's "tiempo" value
 * @method Carrera     setDetalle()           Sets the current record's "detalle" value
 * @method Carrera     setFecha()             Sets the current record's "fecha" value
 * @method Carrera     setHora()              Sets the current record's "hora" value
 * @method Carrera     setEstado()            Sets the current record's "estado" value
 * @method Carrera     setTiempoAtencion()    Sets the current record's "tiempo_atencion" value
 * @method Carrera     setDestino()           Sets the current record's "destino" value
 * @method Carrera     setHoraat()            Sets the current record's "horaat" value
 * @method Carrera     setTiempoAproxDest()   Sets the current record's "tiempo_aprox_dest" value
 * @method Carrera     setHoraDest()          Sets the current record's "hora_dest" value
 * @method Carrera     setCalidad()           Sets the current record's "calidad" value
 * @method Carrera     setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method Carrera     setCodigo()            Sets the current record's "Codigo" value
 * @method Carrera     setVehiculo()          Sets the current record's "Vehiculo" value
 * @method Carrera     setSinCodigo()         Sets the current record's "Sin_Codigo" value
 * @method Carrera     setSector()            Sets the current record's "Sector" value
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarrera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrera');
        $this->hasColumn('id_operador', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('id_codigo', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('id_vehiculo', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('id_sincodigo', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('tiempo', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('detalle', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('estado', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'cancelada',
              1 => 'completada',
              2 => 'espera',
              3 => 'solicitada',
             ),
             ));
        $this->hasColumn('tiempo_atencion', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('destino', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('horaat', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('tiempo_aprox_dest', 'integer', 3, array(
             'type' => 'integer',
             'length' => 3,
             ));
        $this->hasColumn('hora_dest', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('calidad', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id_operador',
             'foreign' => 'id'));

        $this->hasOne('Codigo', array(
             'local' => 'id_codigo',
             'foreign' => 'id'));

        $this->hasOne('Vehiculo', array(
             'local' => 'id_vehiculo',
             'foreign' => 'id'));

        $this->hasOne('Sin_Codigo', array(
             'local' => 'id_sincodigo',
             'foreign' => 'id'));

        $this->hasOne('Sector', array(
             'local' => 'destino',
             'foreign' => 'id'));
    }
}