<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cliente', 'doctrine');

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Codigo
 * 
 * @method Doctrine_Collection getCodigo() Returns the current record's "Codigo" collection
 * @method Cliente             setCodigo() Sets the current record's "Codigo" collection
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends persona
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('cliente');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Codigo', array(
             'local' => 'id',
             'foreign' => 'id_cliente'));
    }
}