<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Codigo', 'doctrine');

/**
 * BaseCodigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_user
 * @property integer $id_cliente
 * @property string $numero
 * @property integer $barrio
 * @property string $calle1
 * @property string $calle2
 * @property string $numCasa
 * @property clob $observacion
 * @property string $latitud
 * @property string $longitud
 * @property Cliente $Cliente
 * @property sfGuardUser $sfGuardUser
 * @property Sector $Sector
 * @property Doctrine_Collection $Carrera
 * @property Doctrine_Collection $Solicitud_Carrera
 * @property Doctrine_Collection $Reservacion
 * 
 * @method integer             getIdUser()            Returns the current record's "id_user" value
 * @method integer             getIdCliente()         Returns the current record's "id_cliente" value
 * @method string              getNumero()            Returns the current record's "numero" value
 * @method integer             getBarrio()            Returns the current record's "barrio" value
 * @method string              getCalle1()            Returns the current record's "calle1" value
 * @method string              getCalle2()            Returns the current record's "calle2" value
 * @method string              getNumCasa()           Returns the current record's "numCasa" value
 * @method clob                getObservacion()       Returns the current record's "observacion" value
 * @method string              getLatitud()           Returns the current record's "latitud" value
 * @method string              getLongitud()          Returns the current record's "longitud" value
 * @method Cliente             getCliente()           Returns the current record's "Cliente" value
 * @method sfGuardUser         getSfGuardUser()       Returns the current record's "sfGuardUser" value
 * @method Sector              getSector()            Returns the current record's "Sector" value
 * @method Doctrine_Collection getCarrera()           Returns the current record's "Carrera" collection
 * @method Doctrine_Collection getSolicitudCarrera()  Returns the current record's "Solicitud_Carrera" collection
 * @method Doctrine_Collection getReservacion()       Returns the current record's "Reservacion" collection
 * @method Codigo              setIdUser()            Sets the current record's "id_user" value
 * @method Codigo              setIdCliente()         Sets the current record's "id_cliente" value
 * @method Codigo              setNumero()            Sets the current record's "numero" value
 * @method Codigo              setBarrio()            Sets the current record's "barrio" value
 * @method Codigo              setCalle1()            Sets the current record's "calle1" value
 * @method Codigo              setCalle2()            Sets the current record's "calle2" value
 * @method Codigo              setNumCasa()           Sets the current record's "numCasa" value
 * @method Codigo              setObservacion()       Sets the current record's "observacion" value
 * @method Codigo              setLatitud()           Sets the current record's "latitud" value
 * @method Codigo              setLongitud()          Sets the current record's "longitud" value
 * @method Codigo              setCliente()           Sets the current record's "Cliente" value
 * @method Codigo              setSfGuardUser()       Sets the current record's "sfGuardUser" value
 * @method Codigo              setSector()            Sets the current record's "Sector" value
 * @method Codigo              setCarrera()           Sets the current record's "Carrera" collection
 * @method Codigo              setSolicitudCarrera()  Sets the current record's "Solicitud_Carrera" collection
 * @method Codigo              setReservacion()       Sets the current record's "Reservacion" collection
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCodigo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('codigo');
        $this->hasColumn('id_user', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('id_cliente', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('numero', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 5,
             ));
        $this->hasColumn('barrio', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('calle1', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('calle2', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('numCasa', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('observacion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('latitud', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('longitud', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Cliente', array(
             'local' => 'id_cliente',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'id_user',
             'foreign' => 'id'));

        $this->hasOne('Sector', array(
             'local' => 'barrio',
             'foreign' => 'id'));

        $this->hasMany('Carrera', array(
             'local' => 'id',
             'foreign' => 'id_codigo'));

        $this->hasMany('Solicitud_Carrera', array(
             'local' => 'id',
             'foreign' => 'id_codigo'));

        $this->hasMany('Reservacion', array(
             'local' => 'id',
             'foreign' => 'id_codigo'));
    }
}