<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Reservacion', 'doctrine');

/**
 * BaseReservacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_codigo
 * @property boolean $lunes
 * @property boolean $martes
 * @property boolean $miercoles
 * @property boolean $jueves
 * @property boolean $viernes
 * @property boolean $sabado
 * @property boolean $domingo
 * @property time $horario1
 * @property time $horario2
 * @property time $horario3
 * @property Codigo $Codigo
 * 
 * @method integer     getIdCodigo()  Returns the current record's "id_codigo" value
 * @method boolean     getLunes()     Returns the current record's "lunes" value
 * @method boolean     getMartes()    Returns the current record's "martes" value
 * @method boolean     getMiercoles() Returns the current record's "miercoles" value
 * @method boolean     getJueves()    Returns the current record's "jueves" value
 * @method boolean     getViernes()   Returns the current record's "viernes" value
 * @method boolean     getSabado()    Returns the current record's "sabado" value
 * @method boolean     getDomingo()   Returns the current record's "domingo" value
 * @method time        getHorario1()  Returns the current record's "horario1" value
 * @method time        getHorario2()  Returns the current record's "horario2" value
 * @method time        getHorario3()  Returns the current record's "horario3" value
 * @method Codigo      getCodigo()    Returns the current record's "Codigo" value
 * @method Reservacion setIdCodigo()  Sets the current record's "id_codigo" value
 * @method Reservacion setLunes()     Sets the current record's "lunes" value
 * @method Reservacion setMartes()    Sets the current record's "martes" value
 * @method Reservacion setMiercoles() Sets the current record's "miercoles" value
 * @method Reservacion setJueves()    Sets the current record's "jueves" value
 * @method Reservacion setViernes()   Sets the current record's "viernes" value
 * @method Reservacion setSabado()    Sets the current record's "sabado" value
 * @method Reservacion setDomingo()   Sets the current record's "domingo" value
 * @method Reservacion setHorario1()  Sets the current record's "horario1" value
 * @method Reservacion setHorario2()  Sets the current record's "horario2" value
 * @method Reservacion setHorario3()  Sets the current record's "horario3" value
 * @method Reservacion setCodigo()    Sets the current record's "Codigo" value
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReservacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reservacion');
        $this->hasColumn('id_codigo', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('lunes', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('martes', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('miercoles', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('jueves', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('viernes', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('sabado', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('domingo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('horario1', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('horario2', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('horario3', 'time', null, array(
             'type' => 'time',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Codigo', array(
             'local' => 'id_codigo',
             'foreign' => 'id'));
    }
}