<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Solicitud_Carrera', 'doctrine');

/**
 * BaseSolicitud_Carrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_codigo
 * @property integer $id_cliente
 * @property enum $estado
 * @property integer $tiempo
 * @property clob $detalle
 * @property date $fecha
 * @property time $hora
 * @property string $notificacion
 * @property Codigo $Codigo
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer           getIdCodigo()     Returns the current record's "id_codigo" value
 * @method integer           getIdCliente()    Returns the current record's "id_cliente" value
 * @method enum              getEstado()       Returns the current record's "estado" value
 * @method integer           getTiempo()       Returns the current record's "tiempo" value
 * @method clob              getDetalle()      Returns the current record's "detalle" value
 * @method date              getFecha()        Returns the current record's "fecha" value
 * @method time              getHora()         Returns the current record's "hora" value
 * @method string            getNotificacion() Returns the current record's "notificacion" value
 * @method Codigo            getCodigo()       Returns the current record's "Codigo" value
 * @method sfGuardUser       getSfGuardUser()  Returns the current record's "sfGuardUser" value
 * @method Solicitud_Carrera setIdCodigo()     Sets the current record's "id_codigo" value
 * @method Solicitud_Carrera setIdCliente()    Sets the current record's "id_cliente" value
 * @method Solicitud_Carrera setEstado()       Sets the current record's "estado" value
 * @method Solicitud_Carrera setTiempo()       Sets the current record's "tiempo" value
 * @method Solicitud_Carrera setDetalle()      Sets the current record's "detalle" value
 * @method Solicitud_Carrera setFecha()        Sets the current record's "fecha" value
 * @method Solicitud_Carrera setHora()         Sets the current record's "hora" value
 * @method Solicitud_Carrera setNotificacion() Sets the current record's "notificacion" value
 * @method Solicitud_Carrera setCodigo()       Sets the current record's "Codigo" value
 * @method Solicitud_Carrera setSfGuardUser()  Sets the current record's "sfGuardUser" value
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSolicitud_Carrera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('solicitud_carrera');
        $this->hasColumn('id_codigo', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('id_cliente', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('estado', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'solicitada',
              1 => 'aprovada',
              2 => 'negada',
              3 => 'cancelada',
             ),
             'default' => 'nueva',
             ));
        $this->hasColumn('tiempo', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('detalle', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('notificacion', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Codigo', array(
             'local' => 'id_codigo',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'id_cliente',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}