<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Peticion_Codigo', 'doctrine');

/**
 * BasePeticion_Codigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePeticion_Codigo extends Codigo
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('peticion_codigo');
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}