<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sin_Codigo', 'doctrine');

/**
 * BaseSin_Codigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cliente
 * @property string $telefono
 * @property integer $barrio
 * @property string $calle1
 * @property string $calle2
 * @property string $numCasa
 * @property clob $observacion
 * @property Sector $Sector
 * @property Doctrine_Collection $Carrera
 * 
 * @method string              getCliente()     Returns the current record's "cliente" value
 * @method string              getTelefono()    Returns the current record's "telefono" value
 * @method integer             getBarrio()      Returns the current record's "barrio" value
 * @method string              getCalle1()      Returns the current record's "calle1" value
 * @method string              getCalle2()      Returns the current record's "calle2" value
 * @method string              getNumCasa()     Returns the current record's "numCasa" value
 * @method clob                getObservacion() Returns the current record's "observacion" value
 * @method Sector              getSector()      Returns the current record's "Sector" value
 * @method Doctrine_Collection getCarrera()     Returns the current record's "Carrera" collection
 * @method Sin_Codigo          setCliente()     Sets the current record's "cliente" value
 * @method Sin_Codigo          setTelefono()    Sets the current record's "telefono" value
 * @method Sin_Codigo          setBarrio()      Sets the current record's "barrio" value
 * @method Sin_Codigo          setCalle1()      Sets the current record's "calle1" value
 * @method Sin_Codigo          setCalle2()      Sets the current record's "calle2" value
 * @method Sin_Codigo          setNumCasa()     Sets the current record's "numCasa" value
 * @method Sin_Codigo          setObservacion() Sets the current record's "observacion" value
 * @method Sin_Codigo          setSector()      Sets the current record's "Sector" value
 * @method Sin_Codigo          setCarrera()     Sets the current record's "Carrera" collection
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSin_Codigo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sin_codigo');
        $this->hasColumn('cliente', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('telefono', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('barrio', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('calle1', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('calle2', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('numCasa', 'string', 8, array(
             'type' => 'string',
             'length' => 8,
             ));
        $this->hasColumn('observacion', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sector', array(
             'local' => 'barrio',
             'foreign' => 'id'));

        $this->hasMany('Carrera', array(
             'local' => 'id',
             'foreign' => 'id_sincodigo'));
    }
}