<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Persona', 'doctrine');

/**
 * BasePersona
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $sexo
 * @property string $direccion
 * @property string $telefono
 * @property string $telefonoMovil
 * 
 * @method string  getFirstName()     Returns the current record's "first_name" value
 * @method string  getLastName()      Returns the current record's "last_name" value
 * @method string  getSexo()          Returns the current record's "sexo" value
 * @method string  getDireccion()     Returns the current record's "direccion" value
 * @method string  getTelefono()      Returns the current record's "telefono" value
 * @method string  getTelefonoMovil() Returns the current record's "telefonoMovil" value
 * @method Persona setFirstName()     Sets the current record's "first_name" value
 * @method Persona setLastName()      Sets the current record's "last_name" value
 * @method Persona setSexo()          Sets the current record's "sexo" value
 * @method Persona setDireccion()     Sets the current record's "direccion" value
 * @method Persona setTelefono()      Sets the current record's "telefono" value
 * @method Persona setTelefonoMovil() Sets the current record's "telefonoMovil" value
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersona extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('persona');
        $this->hasColumn('first_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'M',
             'length' => 1,
             ));
        $this->hasColumn('direccion', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('telefono', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('telefonoMovil', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}