<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Propietario', 'doctrine');

/**
 * BasePropietario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cedula
 * @property string $licencia
 * @property Doctrine_Collection $Vehiculo
 * 
 * @method string              getCedula()   Returns the current record's "cedula" value
 * @method string              getLicencia() Returns the current record's "licencia" value
 * @method Doctrine_Collection getVehiculo() Returns the current record's "Vehiculo" collection
 * @method Propietario         setCedula()   Sets the current record's "cedula" value
 * @method Propietario         setLicencia() Sets the current record's "licencia" value
 * @method Propietario         setVehiculo() Sets the current record's "Vehiculo" collection
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePropietario extends persona
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('propietario');
        $this->hasColumn('cedula', 'string', 10, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('licencia', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Vehiculo', array(
             'local' => 'id',
             'foreign' => 'id_propietario'));
    }
}