<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Vehiculo', 'doctrine');

/**
 * BaseVehiculo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_propietario
 * @property integer $id_sector
 * @property string $numero
 * @property string $placa
 * @property string $marca
 * @property string $modelo
 * @property string $ano
 * @property Propietario $Propietario
 * @property Sector $Sector
 * @property Doctrine_Collection $Carrera
 * 
 * @method integer             getIdPropietario()  Returns the current record's "id_propietario" value
 * @method integer             getIdSector()       Returns the current record's "id_sector" value
 * @method string              getNumero()         Returns the current record's "numero" value
 * @method string              getPlaca()          Returns the current record's "placa" value
 * @method string              getMarca()          Returns the current record's "marca" value
 * @method string              getModelo()         Returns the current record's "modelo" value
 * @method string              getAno()            Returns the current record's "ano" value
 * @method Propietario         getPropietario()    Returns the current record's "Propietario" value
 * @method Sector              getSector()         Returns the current record's "Sector" value
 * @method Doctrine_Collection getCarrera()        Returns the current record's "Carrera" collection
 * @method Vehiculo            setIdPropietario()  Sets the current record's "id_propietario" value
 * @method Vehiculo            setIdSector()       Sets the current record's "id_sector" value
 * @method Vehiculo            setNumero()         Sets the current record's "numero" value
 * @method Vehiculo            setPlaca()          Sets the current record's "placa" value
 * @method Vehiculo            setMarca()          Sets the current record's "marca" value
 * @method Vehiculo            setModelo()         Sets the current record's "modelo" value
 * @method Vehiculo            setAno()            Sets the current record's "ano" value
 * @method Vehiculo            setPropietario()    Sets the current record's "Propietario" value
 * @method Vehiculo            setSector()         Sets the current record's "Sector" value
 * @method Vehiculo            setCarrera()        Sets the current record's "Carrera" collection
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVehiculo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehiculo');
        $this->hasColumn('id_propietario', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('id_sector', 'integer', 10, array(
             'type' => 'integer',
             'length' => 10,
             ));
        $this->hasColumn('numero', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 10,
             ));
        $this->hasColumn('placa', 'string', 7, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 7,
             ));
        $this->hasColumn('marca', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('modelo', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('ano', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Propietario', array(
             'local' => 'id_propietario',
             'foreign' => 'id'));

        $this->hasOne('Sector', array(
             'local' => 'id_sector',
             'foreign' => 'id'));

        $this->hasMany('Carrera', array(
             'local' => 'id',
             'foreign' => 'id_vehiculo'));
    }
}