# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:  
  .actions:
    error_404_module:    errores
    error_404_action:    index
    error_403_module:    errores
    error_403_action:    error403
    error_401_module:    errores
    error_401_action:    error401
    error_500_module:    errores
    error_500_action:    error500
  
  .settings:
    
    # Form security secret (CSRF protection)
    csrf_secret:            7fcdee544f615d5d4697268a1c3fefa053cf9ec9

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    enabled_modules:        [default, sfGuardAuth, sfGuardRegister, sfGuardForgotPassword, sfGuardGroup, sfGuardPermission, sfGuardUser]
    
    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
    default_culture:        es_EC
    i18n:                   true
    charset:                utf-8