<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/14 22:05:02
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_success_signin_url' => 'homepage',
  'app_sf_guard_plugin_success_signout_url' => 'sf_guard_signout',
  'app_default_is_secure' => true,
  'app_url_pagina' => 'http://radiotaxi.com',
  'app_correo_admin' => 'coop.benjamin.carrion@gmail.com',
  'app_nombre_admin' => 'Radio-Taxi Benjamín Carrión',
));
