<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/14 22:05:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=radiotaxi',
  'username' => 'root',
  'password' => 'edulima1989',
  'name' => 'doctrine',
)),);
