<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/01/05 06:44:16
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
