<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/14 22:05:14
$this->security = array (
  'inicio' => 
  array (
    'is_secure' => true,
    'credentials' => 'operador',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
