<?php
// auto-generated by sfViewConfigHandler
// date: 2013/09/17 12:09:39
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'gestionSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'simulacionSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'sectorSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('charset', 'utf-8', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('tablas3.css', '', array ());
  $response->addStylesheet('jquery-ui-1.7.2.custom.css', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('jquery-ui.min.js', '', array ());
  $response->addJavascript('calendario.js', '', array ());
}
else if ($templateName.$this->viewName == 'gestionSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('charset', 'utf-8', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('carreras.css', '', array ());
  $response->addStylesheet('gestion.css', '', array ());
  $response->addJavascript('jquery.min.js', '', array ());
  $response->addJavascript('gestionCarrera.js', '', array ());
}
else if ($templateName.$this->viewName == 'simulacionSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('charset', 'utf-8', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('jquery.toastmessage.css', '', array ());
  $response->addStylesheet('reveal.css', '', array ());
  $response->addStylesheet('chosen.css', '', array ());
  $response->addStylesheet('tabs.css', '', array ());
  $response->addStylesheet('central/simulacion.css', '', array ());
  $response->addJavascript('https://maps.google.com/maps/api/js?sensor=true', '', array ());
  $response->addJavascript('gmaps.js', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('jquery.reveal.js', '', array ());
  $response->addJavascript('jquery.toastmessage.js', '', array ());
  $response->addJavascript('jquery-moveme.js', '', array ());
  $response->addJavascript('simulacion.js', '', array ());
  $response->addJavascript('chosen.jquery.min.js', '', array ());
  $response->addJavascript('modernizr.custom.04022.js', '', array ());
}
else if ($templateName.$this->viewName == 'sectorSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('charset', 'utf-8', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('central/sector.css', '', array ());
  $response->addJavascript('https://maps.google.com/maps/api/js?sensor=true', '', array ());
  $response->addJavascript('sector.js', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addHttpMeta('charset', 'utf-8', false);

  $response->addStylesheet('main.css', '', array ());
}

