<?php

/**
 * Carrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Carrera extends BaseCarrera {

    public function getAtencion() {
        $aux = $this->getTiempo() - $this->getTiempoAtencion();
        if ($aux >= -1) {
            return 'RAPIDA';
        }else
            return 'RETRAZO';
    }
    public function getLlegada(){
        $ini = $this->getHoraat();
        $fin = $this->getHoraDest();
        $horai = substr($ini, 0, 2);
        $mini = substr($ini, 3, 2);
        $segi = substr($ini, 6, 2);

        $horaf = substr($fin, 0, 2);
        $minf = substr($fin, 3, 2);
        $segf = substr($fin, 6, 2);

        $segIni = ((($horai * 60) * 60) + ($mini * 60) + $segi);
        $segFin = ((($horaf * 60) * 60) + ($minf * 60) + $segf);
        $time = $segFin - $segIni;
        $time = floor($time/60);
        $tAprox = $this->getTiempoAproxDest();
        if(($time ) < ($tAprox - 2))
            return 'VELOCIDAD';
        else if (($time ) > ($tAprox + 2))
            return 'DEMORA';
        else
            return 'NORMAL';
    }

    public function getNumCodigo() {
        if (is_null($this->getIdCodigo())) {
            return "ocasional";
        } else {
            return $this->getCodigo()->getNumero();
        }
    }

    public function getBarrio() {
        if (is_null($this->getIdCodigo())) {
            return $this->getSin_Codigo()->getSector()->getNombre();
        } else {
            return $this->getCodigo()->getSector()->getNombre();
        }
    }

    public function getLatitud() {
        if (is_null($this->getIdCodigo())) {
            return null;
        } else {
            return $this->getCodigo()->getLatitud();
        }
    }

    public function getLongitud() {
        if (is_null($this->getIdCodigo())) {
            return null;
        } else {
            return $this->getCodigo()->getLongitud();
        }
    }

    public function getSector() {
        if (is_null($this->getIdCodigo())) {
            return $this->getSin_Codigo()->getBarrio();
        } else {
            return $this->getCodigo()->getBarrio();
        }
    }

    public function getCalle1() {
        if (is_null($this->getIdCodigo())) {
            return $this->getSin_Codigo()->getCalle1();
        } else {
            return $this->getCodigo()->getCalle1();
        }
    }

    public function getCalle2() {
        if (is_null($this->getIdCodigo())) {
            return $this->getSin_Codigo()->getCalle2();
        } else {
            return $this->getCodigo()->getCalle2();
        }
    }
    
    public function getReferencia(){
        if (is_null($this->getIdCodigo())) {
            return $this->getSin_Codigo()->getObservacion();
        } else {
            return $this->getCodigo()->getObservacion();
        }
    }

    public function getNombreCliente() {
        if (is_null($this->getIdCodigo())) {
            return $this->getSin_Codigo()->getCliente();
        } else {
            return $this->getCodigo()->getNombreCliente();
        }
    }

    public function getLinkCodigo() {
        if (is_null($this->getIdCodigo())) {
            return url_for('codigoOcacional/show?id=' . $this->getIdSincodigo());
        } else {
            return url_for('codigo/datos?id=' . $this->getIdCodigo());
        }
    }

    public function getCodigoId() {
        if (is_null($this->getIdCodigo())) {
            return $this->getIdSincodigo();
        } else {
            return $this->getIdCodigo();
        }
    }

}