<?php

/**
 * CarreraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarreraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarreraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Carrera');
    }
}