<?php

/**
 * CodigoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CodigoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CodigoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Codigo');
    }
}