<?php

/**
 * Codigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    radiotaxi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Codigo extends BaseCodigo {

    public function __toString() {
        return $this->getNumero();
    }

    public function obtenerBarrio(){
        return $this->getSector();
    }


    public function getNombreCliente() {
        if (is_null($this->getIdCliente())) {
            return $this->getSfGuardUser()->getFirstName() . ' ' . $this->getSfGuardUser()->getLastName();
        } else {
            return $this->getCliente()->getFirstName() . ' ' . $this->getCliente()->getLastName();
        }
    }

    public function getNombreClienteId() {
        if (is_null($this->getIdCliente())) {
            return $this->getIdSfGuardUser();
        } else {
            return $this->getIdCliente();
        }
    }

    public function getUrlGuardar() {
        if (is_null($this->getIdCliente())) {
            return 'codigo/show?id=' . $this->getId();
        } else {
            return 'cliente/show?id=' . $this->getIdCliente();
        }
    }

    public function getUrlEliminar() {
        if (is_null($this->getIdCliente())) {
            return 'codigo/index';
        } else {
            return 'cliente/show?id=' . $this->getIdCliente();
        }
    }

}