<?php

/**
 * Peticion_CodigoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Peticion_CodigoTable extends CodigoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Peticion_CodigoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Peticion_Codigo');
    }
}