<?php

/**
 * PeticionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeticionTable extends personaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeticionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Peticion');
    }
}