<?php

/**
 * PropietarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropietarioTable extends personaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropietarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Propietario');
    }
}