<?php

/**
 * Sin_CodigoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Sin_CodigoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Sin_CodigoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sin_Codigo');
    }
}