<?php

/**
 * Solicitud_CarreraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Solicitud_CarreraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Solicitud_CarreraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Solicitud_Carrera');
    }
}