<?php

/**
 * VehiculoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehiculoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VehiculoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vehiculo');
    }
}