// Funcion Javascript para obtener los temas de ayuda
function mostrardiuser(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","block");$("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","none");$("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","none");}	
function mostrardiproyecto(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none");  $("#proyectos").css("display","block"); $("#objectives").css("display","none"); $("#activities").css("display","none"); $("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","none"); }
function mostrardiobjetivos(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","block"); $("#activities").css("display","none"); $("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","none"); }
function mostrardiactividades(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","block"); $("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","none"); }
function mostrardirubros(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","none"); $("#rubrs").css("display","block"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","none");}
function mostrardidescripciones(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","none"); $("#rubrs").css("display","none"); $("#descrip").css("display","block"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","none");}
function mostrardientidades(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","none"); $("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","block"); $("#Reportes").css("display","none"); $("#help").css("display","none");}
function mostrardireportes(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","none");  $("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","block"); $("#help").css("display","none");}
function mostrardiayudas(){ $("#PaginaDefecto").css("display","none"); $("#usuarios").css("display","none"); $("#proyectos").css("display","none"); $("#objectives").css("display","none"); $("#activities").css("display","none"); $("#rubrs").css("display","none"); $("#descrip").css("display","none"); $("#enty").css("display","none"); $("#Reportes").css("display","none"); $("#help").css("display","block");}


function mostrardiadministrador(){ $("#administrador").css("display","block"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","none"); $("#peticiones").css("display","none"); $("#techos").css("display","none"); $("#grupos").css("display","none"); $("#permisos").css("display","none");$("#ayudasad").css("display","none");}	
function mostrardimanager(){ $("#administrador").css("display","none"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","block"); $("#peticiones").css("display","none"); $("#techos").css("display","none"); $("#grupos").css("display","none"); $("#permisos").css("display","none");$("#ayudasad").css("display","none");}
function mostrardipeticiones(){ $("#administrador").css("display","none"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","none"); $("#peticiones").css("display","block"); $("#techos").css("display","none"); $("#grupos").css("display","none"); $("#permisos").css("display","none");$("#ayudasad").css("display","none");}
function mostrarditechos(){ $("#administrador").css("display","none"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","none"); $("#peticiones").css("display","none"); $("#techos").css("display","block"); $("#grupos").css("display","none"); $("#permisos").css("display","none");$("#ayudasad").css("display","none");}
function mostrardigrupos(){ $("#administrador").css("display","none"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","none"); $("#peticiones").css("display","none"); $("#techos").css("display","none"); $("#grupos").css("display","block"); $("#permisos").css("display","none");$("#ayudasad").css("display","none");}
function mostrardipermisos(){ $("#administrador").css("display","none"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","none"); $("#peticiones").css("display","none"); $("#techos").css("display","none"); $("#grupos").css("display","none"); $("#permisos").css("display","block");$("#ayudasad").css("display","none");}
function mostrardiayudaad(){ $("#administrador").css("display","none"); $("#PaginaDefecto").css("display","none"); $("#manager").css("display","none"); $("#peticiones").css("display","none"); $("#techos").css("display","none"); $("#grupos").css("display","none"); $("#permisos").css("display","none"); $("#ayudasad").css("display","block");}
	  