<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/17 16:17:19

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=radiotaxi',
  'username' => 'root',
  'password' => 'edulima1989',
  'name' => 'doctrine',
)),);
