<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/25 19:58:06
sfConfig::add(array(
  'mod_solicitarcodigo_enabled' => true,
  'mod_solicitarcodigo_view_class' => 'sfPHP',
));
