<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/17 22:14:13
sfConfig::add(array(
  'mod_carrerapeticion_enabled' => true,
  'mod_carrerapeticion_view_class' => 'sfPHP',
));
