<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/17 22:14:07
$this->security = array (
  'contactenos' => 
  array (
    'is_secure' => false,
  ),
  'inicio' => 
  array (
    'is_secure' => false,
  ),
  'servicios' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'cliente',
  ),
);
