<?php
// auto-generated by sfViewConfigHandler
// date: 2013/09/17 16:17:19
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout3' ? false : 'layout3'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('error.css', '', array ());
  $response->addJavascript('jquery.min.js', '', array ());
  $response->addJavascript('jas.js', '', array ());
  $response->addJavascript('jquery.reveal.js', '', array ());
  $response->addJavascript('tabs.js', '', array ());
  $response->addJavascript('mostrartemasayuda.js', '', array ());


