<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/14 18:42:17
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => false,
  'app_default_is_secure' => true,
  'app_url_pagina' => 'http://radiotaxi.com',
  'app_correo_admin' => 'coop.benjamin.carrion@gmail.com',
  'app_nombre_admin' => 'Radio-Taxi Benjamín Carrión',
  'app_rbd_name' => 'radiotaxi',
  'app_rbd_host' => 'localhost',
  'app_rbd_user' => 'root',
  'app_rbd_password' => 'edulima1989',
));
