<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/01/05 06:44:06
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 'administracion',
  ),
);
