<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/20 18:12:35
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'administracion',
  ),
);
