<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/14 22:20:20
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'administracion',
  ),
);
