<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/20 17:21:11
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'administracion',
  ),
);
