<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/11/26 05:29:41
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'administracion',
  ),
);
