<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/20 18:07:20
sfConfig::add(array(
  'mod_peticioncodigo_enabled' => true,
  'mod_peticioncodigo_view_class' => 'sfPHP',
));
