<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/10/08 18:33:26
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'administracion',
  ),
);
