## YAML Template.
default:
  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout


indexSuccess:
  stylesheets: [tablas3.css]
   
newSuccess:
  stylesheets: [central/sector.css]
  javascripts: [https://maps.google.com/maps/api/js?sensor=true , sector.js,jquery-1.7.2.min.js]
  
editSuccess:
  stylesheets: [central/sector.css]
  javascripts: [https://maps.google.com/maps/api/js?sensor=true , sector.js,jquery-1.7.2.min.js]