## YAML Template.
default:
  stylesheets:    [main.css]
showSuccess:
  stylesheets: [maps.css]
  javascripts: [https://maps.google.com/maps/api/js?sensor=true , gmaps.js]
  layout: mostrardatos
  